# Generated by Django 5.0.6 on 2024-07-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=30)),
                ('apellido', models.CharField(help_text='Apellido de la persona', max_length=30)),
                ('email', models.EmailField(help_text='Correo electrónico de la persona', max_length=254, unique=True)),
                ('contraseña', models.CharField(help_text='Contraseña de la persona', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
